mmas.instances.dir=..
mmas.instances=n_1000_1
n_1000_1=n_1000_c_10000000000_g_10_f_0.1_eps_0.0001_s_100
mmas.ants=5
mmas.iterations=20
mmas.alpha=1.0
mmas.beta=2.0
mmas.rho=0.2
mmas.useGlobalBest=true
mmas.localSearch=true
mmas.restartAfter=10
mmas.seed=42
mmas.output.csv=test_results.csv
