mmas.instances.dir=../../../docs/inst_test/instancias
mmas.ants=5
mmas.iterations=20
mmas.alpha=1.0
mmas.beta=2.0
mmas.rho=0.2
mmas.useGlobalBest=true
mmas.localSearch=true
mmas.restartAfter=10
mmas.seed=42
mmas.output.csv=test_results.csv
